import { escapeHtml, formatMobile } from "../utils/html.js";

const badge = (value, tone = value) => `<span class="badge badge-${escapeHtml(tone)}">${escapeHtml(value.replaceAll("_", " "))}</span>`;
const modal = (title, body, wide = false) => `<div class="modal-backdrop" data-close-modal><section class="modal ${wide ? "modal-wide" : ""}" role="dialog" aria-modal="true" aria-labelledby="modal-title" data-modal><header class="modal-header"><h2 id="modal-title">${escapeHtml(title)}</h2><button class="icon-button" type="button" data-close-modal aria-label="Close">×</button></header>${body}</section></div>`;
const groupOptions = (groups, selected = []) => groups.map((group) => `<label class="check-row"><input type="checkbox" name="group_ids" value="${group.id}" ${selected.includes(group.id) ? "checked" : ""}> <span>${escapeHtml(group.name)}</span></label>`).join("");

export function dashboardView({ organization, contacts, eligible, groups, announcements }) {
  const nowMonth = new Date().toISOString().slice(0, 7);
  const current = announcements.filter(({ created_at }) => created_at.startsWith(nowMonth));
  const sent = current.length; const segments = current.reduce((sum, item) => sum + item.total_sms_segments, 0);
  const delivered = current.reduce((sum, item) => sum + (item.delivered ?? item.recipient_count), 0); const recipients = current.reduce((sum, item) => sum + item.recipient_count, 0);
  const percentage = recipients ? `${(delivered / recipients * 100).toFixed(1)}%` : "—";
  return `<header class="page-header"><div><p class="eyebrow">Organization dashboard</p><h1>${escapeHtml(organization.short_name)} overview</h1><p class="muted">A clear view of your roster and announcement activity.</p></div><a class="button button-accent" href="#/announcements">+ New Announcement</a></header>
  <div class="card-grid metrics" aria-label="Organization metrics"><article class="card"><span class="muted">Active contacts</span><p class="metric">${contacts.filter(({ status }) => status === "active").length}</p></article><article class="card"><span class="muted">Eligible contacts</span><p class="metric">${eligible}</p></article><article class="card"><span class="muted">Announcements this month</span><p class="metric">${sent}</p></article><article class="card"><span class="muted">SMS segments used</span><p class="metric">${segments}</p></article><article class="card"><span class="muted">Delivery rate</span><p class="metric">${percentage}</p></article></div>
  <section class="card section-card"><div class="section-heading"><div><h2>Recent announcements</h2><p class="muted">Simulated activity for ${escapeHtml(organization.name)}</p></div><a href="#/history">View history</a></div>${announcements.length ? `<div class="announcement-list">${announcements.slice().sort((a,b) => b.created_at.localeCompare(a.created_at)).slice(0,5).map((item) => `<article><div><strong>${escapeHtml(item.title)}</strong><p>${escapeHtml(item.body)}</p></div><div class="announcement-meta"><span>${new Date(item.created_at).toLocaleDateString("en-CA", { month: "short", day: "numeric" })}</span><span>${item.recipient_count} recipients</span>${badge(item.status)}</div></article>`).join("")}</div>` : `<div class="empty-inline">No announcements yet.</div>`}</section>`;
}

export function contactsView({ contacts, groups, memberships, filters, selectedIds, modalContact, showImport, importPreview, importResult, createUnknown }) {
  const membershipMap = new Map(); for (const row of memberships) membershipMap.set(row.contact_id, [...(membershipMap.get(row.contact_id) ?? []), row.group_id]);
  const groupMap = new Map(groups.map((group) => [group.id, group.name]));
  const q = filters.q.toLowerCase(); const filtered = contacts.filter((contact) => (!q || `${contact.first_name} ${contact.last_name} ${contact.mobile}`.toLowerCase().includes(q)) && (!filters.status || contact.status === filters.status) && (!filters.consent || contact.consent_status === filters.consent) && (!filters.group || (membershipMap.get(contact.id) ?? []).includes(filters.group)));
  const body = filtered.map((contact) => `<tr><td data-label="Select"><input type="checkbox" data-select-contact value="${contact.id}" aria-label="Select ${escapeHtml(contact.first_name)} ${escapeHtml(contact.last_name)}" ${selectedIds.has(contact.id) ? "checked" : ""}></td><td data-label="Contact"><button class="text-button contact-name" data-edit-contact="${contact.id}">${escapeHtml(contact.first_name)} ${escapeHtml(contact.last_name)}</button><small>${formatMobile(contact.mobile)}</small></td><td data-label="Groups"><div class="tag-list">${(membershipMap.get(contact.id) ?? []).map((id) => `<span>${escapeHtml(groupMap.get(id))}</span>`).join("") || "—"}</div></td><td data-label="Status">${badge(contact.status)}</td><td data-label="Consent">${badge(contact.consent_status)}</td><td data-label="Updated">${new Date(contact.updated_at).toLocaleDateString("en-CA")}</td><td><button class="icon-button" data-edit-contact="${contact.id}" aria-label="Edit ${escapeHtml(contact.first_name)} ${escapeHtml(contact.last_name)}">•••</button></td></tr>`).join("");
  let overlay = "";
  if (modalContact !== undefined) {
    const contact = modalContact || { first_name: "", last_name: "", mobile: "", status: "active", consent_status: "unknown" }; const assigned = contact.id ? membershipMap.get(contact.id) ?? [] : [];
    overlay = modal(contact.id ? "Edit contact" : "Add contact", `<form id="contact-form" class="form-grid"><input type="hidden" name="id" value="${contact.id ?? ""}"><label>First name<input required name="first_name" value="${escapeHtml(contact.first_name)}"></label><label>Last name<input required name="last_name" value="${escapeHtml(contact.last_name)}"></label><label class="span-2">Mobile<input required name="mobile" inputmode="tel" value="${escapeHtml(contact.mobile)}" placeholder="403-555-0123"></label><label>Status<select name="status"><option value="active" ${contact.status === "active" ? "selected" : ""}>Active</option><option value="inactive" ${contact.status === "inactive" ? "selected" : ""}>Inactive</option></select></label><label>Consent<select name="consent_status"><option value="subscribed" ${contact.consent_status === "subscribed" ? "selected" : ""}>Subscribed</option><option value="unsubscribed" ${contact.consent_status === "unsubscribed" ? "selected" : ""}>Unsubscribed</option><option value="unknown" ${contact.consent_status === "unknown" ? "selected" : ""}>Unknown</option></select></label><fieldset class="span-2"><legend>Group memberships</legend><div class="check-grid">${groupOptions(groups, assigned)}</div></fieldset><footer class="modal-actions">${contact.id ? `<button type="button" class="button button-secondary" data-toggle-status="${contact.id}">${contact.status === "active" ? "Deactivate" : "Reactivate"}</button>` : ""}<span></span><button type="button" class="button button-secondary" data-close-modal>Cancel</button><button class="button">Save contact</button></footer></form>`);
  } else if (showImport) overlay = importModal(importPreview, importResult, createUnknown);
  return `<header class="page-header"><div><p class="eyebrow">Roster management</p><h1>Contacts</h1><p class="muted">${contacts.length} contacts · no permanent deletion</p></div><div class="header-actions"><button class="button button-secondary" id="open-import">Import CSV</button><button class="button" id="add-contact">Add contact</button></div></header>
  <section class="card toolbar"><label class="search"><span class="sr-only">Search contacts</span><input id="contact-search" type="search" placeholder="Search name or mobile" value="${escapeHtml(filters.q)}"></label><select id="status-filter" aria-label="Filter by status"><option value="">All statuses</option><option value="active" ${filters.status === "active" ? "selected" : ""}>Active</option><option value="inactive" ${filters.status === "inactive" ? "selected" : ""}>Inactive</option></select><select id="consent-filter" aria-label="Filter by consent"><option value="">All consent</option>${["subscribed","unsubscribed","unknown"].map((v) => `<option value="${v}" ${filters.consent === v ? "selected" : ""}>${v[0].toUpperCase()+v.slice(1)}</option>`).join("")}</select><select id="group-filter" aria-label="Filter by group"><option value="">All groups</option>${groups.map((g) => `<option value="${g.id}" ${filters.group === g.id ? "selected" : ""}>${escapeHtml(g.name)}</option>`).join("")}</select></section>
  ${selectedIds.size ? `<div class="bulk-bar"><strong>${selectedIds.size} selected</strong><select id="bulk-group"><option value="">Choose group…</option>${groups.map((g) => `<option value="${g.id}">${escapeHtml(g.name)}</option>`).join("")}</select><button class="button" id="bulk-assign">Add to group</button><button class="text-button" id="clear-selection">Clear</button></div>` : ""}
  <section class="table-card"><div class="table-scroll"><table><thead><tr><th><span class="sr-only">Select</span></th><th>Contact</th><th>Groups</th><th>Status</th><th>Consent</th><th>Updated</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody>${body || `<tr><td colspan="7" class="empty-inline">No contacts match these filters.</td></tr>`}</tbody></table></div><footer class="table-footer">Showing ${filtered.length} of ${contacts.length} contacts</footer></section>${overlay}`;
}

function importModal(preview, result, createUnknown) {
  if (result) return modal("Import complete", `<div class="import-summary success-panel"><p class="metric">${result.imported.length}</p><h3>contacts imported</h3><p>${result.skipped.length} rows skipped · ${result.created_groups.length} groups created</p></div><footer class="modal-actions"><span></span><button class="button" data-close-modal>Done</button></footer>`, true);
  const step = preview ? "Preview and resolve" : "Choose CSV file";
  let body = `<div class="stepper"><span class="complete">Choose</span><span class="${preview ? "complete" : ""}">Preview</span><span>Resolve</span><span>Confirm</span></div><h3>${step}</h3>`;
  if (!preview) body += `<div class="upload-zone"><input id="csv-file" type="file" accept=".csv,text/csv"><strong>Select a CSV roster</strong><p>Required columns: first_name, last_name, mobile, groups</p></div><p class="muted">Nothing is written until you review and confirm the import.</p>`;
  else {
    const issueLabels = { missing_required: "Missing required field", invalid_mobile: "Invalid mobile", duplicate_in_file: "Duplicate in file", existing_contact: "Existing contact", unknown_groups: "Unknown group" };
    body += `<div class="import-stats"><strong>${preview.rows.length} rows</strong><span>${preview.counts.ready} ready</span><span>${preview.counts.issues} need attention</span></div>`;
    if (preview.unknown_groups.length) body += `<section class="resolution-panel"><h3>Unknown groups</h3><p>Choose which groups to create during import. They will not be created until confirmation.</p>${preview.unknown_groups.map((name) => `<label class="check-row"><input type="checkbox" data-create-group value="${escapeHtml(name)}" ${createUnknown.has(name) ? "checked" : ""}> Create “${escapeHtml(name)}”</label>`).join("")}</section>`;
    body += `<div class="table-scroll import-table"><table><thead><tr><th>Row</th><th>Contact</th><th>Mobile</th><th>Groups</th><th>Review</th></tr></thead><tbody>${preview.rows.map((row) => `<tr><td>${row.row_number}</td><td>${escapeHtml(row.first_name)} ${escapeHtml(row.last_name)}</td><td>${escapeHtml(row.mobile ?? row.raw_mobile)}</td><td>${escapeHtml(row.groups.join(", ") || "—")}</td><td><div class="issue-list">${row.issues.length ? row.issues.map((issue) => badge(issueLabels[issue], issue === "unknown_groups" ? "warning" : "danger")).join("") : badge("Ready", "active")}</div></td></tr>`).join("")}</tbody></table></div><footer class="modal-actions"><button class="button button-secondary" id="choose-another">Choose another</button><span></span><button class="button button-secondary" data-close-modal>Cancel</button><button class="button" id="confirm-import">Confirm import</button></footer>`;
  }
  return modal("Import contacts", body, true);
}

export function groupsView({ groups, contacts, memberships, modalGroup }) {
  const counts = new Map(groups.map((group) => [group.id, memberships.filter((row) => row.group_id === group.id).length]));
  let overlay = "";
  if (modalGroup !== undefined) {
    const group = modalGroup || { name: "" }; const members = group.id ? memberships.filter((row) => row.group_id === group.id).map((row) => row.contact_id) : [];
    overlay = modal(group.id ? "Manage group" : "Create group", `<form id="group-form"><input type="hidden" name="id" value="${group.id ?? ""}"><label>Group name<input required name="name" value="${escapeHtml(group.name)}" placeholder="e.g. Training Committee"></label>${group.id ? `<fieldset><legend>Members</legend><div class="member-picker">${contacts.map((contact) => `<label class="check-row"><input type="checkbox" name="contact_ids" value="${contact.id}" ${members.includes(contact.id) ? "checked" : ""}><span>${escapeHtml(contact.first_name)} ${escapeHtml(contact.last_name)} <small>${formatMobile(contact.mobile)}</small></span></label>`).join("")}</div></fieldset>` : `<p class="muted">Create the group first, then add members.</p>`}<footer class="modal-actions"><span></span><button type="button" class="button button-secondary" data-close-modal>Cancel</button><button class="button">Save group</button></footer></form>`, true);
  }
  return `<header class="page-header"><div><p class="eyebrow">Roster organization</p><h1>Groups</h1><p class="muted">All Members is dynamic and always reflects the organization roster.</p></div><button class="button" id="add-group">Create group</button></header><div class="system-group card"><div><span class="system-label">Dynamic selection</span><h2>All Members</h2><p>Automatically includes all ${contacts.length} contacts before eligibility rules.</p></div><span class="metric">${contacts.length}</span></div><div class="group-grid">${groups.map((group) => `<article class="card group-card"><div><h2>${escapeHtml(group.name)}</h2><p class="muted">${counts.get(group.id)} members</p></div><button class="button button-secondary" data-edit-group="${group.id}">Manage</button></article>`).join("")}</div>${overlay}`;
}
